In [87]:
import pandas as pd
import numpy as np

In [104]:
np.random.seed(1)
data_50 =pd.DataFrame({"birth_place"  : np.random.choice(range(1,3),50, replace=True),
"fin_back"  : np.random.choice(['<60k','61k-200k','200k-500k','>501k'],50, replace=True),
"medium"  : np.random.choice(['english','hindi','both'],50, replace=True),
"performace"  : np.random.choice(['<40','41-60','61-75','76-90','>91'],50, replace=True),
"board"  : np.random.choice(['ISC','CBSE','State'],50, replace=True),
"school"  : np.random.choice(['public','private'],50, replace=True),
"stream"  : np.random.choice(['arts','cs','science','commerce'],50, replace=True),
"co-curr"  : np.random.choice(['yes','no'],50, replace=True),
"extra-curr"  : np.random.choice(['yes','no'],50, replace=True),
"school_location"  : np.random.choice(range(1,3),50, replace=True),
"fameSchool"  : np.random.choice(range(1,5),50, replace=True),
"interestedDomain"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],50, replace=True),
"rateOnCurrDomain"  : np.random.choice(range(1,5),50, replace=True),
"profCerti"  : np.random.choice(['yes','no'],50, replace=True),
"personalDevCerti"  : np.random.choice(['yes','no'],50, replace=True),
"languages"  : np.random.choice(range(1,4),50, replace=True),
"personality"  : np.random.choice(['authoritative','helping','reserved','management','freelancing','receivingOrders'],50, replace=True),
"hoursPerDay"  : np.random.choice(range(1,24),50, replace=True),
"job/study"  : np.random.choice(['Job','HigherStudies'],50, replace=True),
"learningMode"  : np.random.choice(['Self','Guided'],50, replace=True),
"SuggestedCarrer"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],50, replace=True)})
# "X1" : np.where(np.random.normal(0.0, 1.0, size=20)<=0,0,1)

In [121]:
np.random.seed(149)
data_50 =pd.DataFrame({"birth_place"  : np.random.choice(range(1,3),500, replace=True),
"fin_back"  : np.random.choice(['<60k','61k-200k','200k-500k','>501k'],500, replace=True),
"medium"  : np.random.choice(['english','hindi','both'],500, replace=True),
"performace"  : np.random.choice(['<40','41-60','61-75','76-90','>91'],500, replace=True),
"board"  : np.random.choice(['ISC','CBSE','State'],500, replace=True),
"school"  : np.random.choice(['public','private'],500, replace=True),
"stream"  : np.random.choice(['arts','cs','science','commerce'],500, replace=True),
"co-curr"  : np.random.choice(['yes','no'],500, replace=True),
"extra-curr"  : np.random.choice(['yes','no'],500, replace=True),
"school_location"  : np.random.choice(range(1,3),500, replace=True),
"fameSchool"  : np.random.choice(range(1,5),500, replace=True),
"interestedDomain"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],500, replace=True),
"rateOnCurrDomain"  : np.random.choice(range(1,5),500, replace=True),
"profCerti"  : np.random.choice(['yes','no'],500, replace=True),
"personalDevCerti"  : np.random.choice(['yes','no'],500, replace=True),
"languages"  : np.random.choice(range(1,4),500, replace=True),
"personality"  : np.random.choice(['authoritative','helping','reserved','management','freelancing','receivingOrders'],500, replace=True),
"hoursPerDay"  : np.random.choice(range(1,24),500, replace=True),
"job/study"  : np.random.choice(['Job','HigherStudies'],500, replace=True),
"learningMode"  : np.random.choice(['Self','Guided'],500, replace=True),
"SuggestedCarrer"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],500, replace=True)})

In [137]:
np.random.seed(128)
data_50 =pd.DataFrame({"birth_place"  : np.random.choice(range(1,3),50000, replace=True),
"fin_back"  : np.random.choice(['<60k','61k-200k','200k-500k','>501k'],50000, replace=True),
"medium"  : np.random.choice(['english','hindi','both'],50000, replace=True),
"performace"  : np.random.choice(['<40','41-60','61-75','76-90','>91'],50000, replace=True),
"board"  : np.random.choice(['ISC','CBSE','State'],50000, replace=True),
"school"  : np.random.choice(['public','private'],50000, replace=True),
"stream"  : np.random.choice(['arts','cs','science','commerce'],50000, replace=True),
"co-curr"  : np.random.choice(['yes','no'],50000, replace=True),
"extra-curr"  : np.random.choice(['yes','no'],50000, replace=True),
"school_location"  : np.random.choice(range(1,3),50000, replace=True),
"fameSchool"  : np.random.choice(range(1,5),50000, replace=True),
"interestedDomain"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],50000, replace=True),
"rateOnCurrDomain"  : np.random.choice(range(1,5),50000, replace=True),
"profCerti"  : np.random.choice(['yes','no'],50000, replace=True),
"personalDevCerti"  : np.random.choice(['yes','no'],50000, replace=True),
"languages"  : np.random.choice(range(1,4),50000, replace=True),
"personality"  : np.random.choice(['authoritative','helping','reserved','management','freelancing','receivingOrders'],50000, replace=True),
"hoursPerDay"  : np.random.choice(range(1,24),50000, replace=True),
"job/study"  : np.random.choice(['Job','HigherStudies'],50000, replace=True),
"learningMode"  : np.random.choice(['Self','Guided'],50000, replace=True),
"SuggestedCarrer"  : np.random.choice(['aerospace','agriculture','automobile','banking','beauty','construction','arts','defence','education','tech','medical','law','management','design','media','civilSercies','Research','humanities','tourism'],50000, replace=True)})

In [138]:
data_50.head()

birth_place   fin_back medium performace  board   school    stream co-curr  \
0            1      >501k   both        <40  State  private   science     yes   
1            2  200k-500k   both      76-90    ISC   public        cs     yes   
2            2   61k-200k   both        <40    ISC   public   science      no   
3            1  200k-500k  hindi      41-60   CBSE   public      arts      no   
4            2  200k-500k   both        >91    ISC  private  commerce     yes   

  extra-curr  school_location  ...  interestedDomain rateOnCurrDomain  \
0         no                2  ...         education                3   
1        yes                2  ...        humanities                1   
2        yes                1  ...        management                3   
3        yes                1  ...           medical                3   
4        yes                2  ...       agriculture                1   

   profCerti personalDevCerti languages  personality hoursPerDay  \
0         no               no         2  freelancing          17   
1        yes              yes         3     reserved           1   
2        yes              yes         2   management           5   
3        yes               no         3   management           2   
4        yes              yes         2      helping          12   

       job/study learningMode SuggestedCarrer  
0            Job         Self        Research  
1            Job         Self       aerospace  
2  HigherStudies       Guided      management  
3            Job       Guided         medical  
4  HigherStudies       Guided         tourism  

[5 rows x 21 columns]

In [139]:
data_50_orig = data_50.copy()

In [140]:
data_50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   birth_place       50000 non-null  int32 
 1   fin_back          50000 non-null  object
 2   medium            50000 non-null  object
 3   performace        50000 non-null  object
 4   board             50000 non-null  object
 5   school            50000 non-null  object
 6   stream            50000 non-null  object
 7   co-curr           50000 non-null  object
 8   extra-curr        50000 non-null  object
 9   school_location   50000 non-null  int32 
 10  fameSchool        50000 non-null  int32 
 11  interestedDomain  50000 non-null  object
 12  rateOnCurrDomain  50000 non-null  int32 
 13  profCerti         50000 non-null  object
 14  personalDevCerti  50000 non-null  object
 15  languages         50000 non-null  int32 
 16  personality       50000 non-null  object
 17  hoursPerDay 

In [141]:
data_50["fin_back"] = data_50["fin_back"].astype('category')
data_50["medium"] = data_50["medium"].astype('category')
data_50["performace"] = data_50["performace"].astype('category')
data_50["board"] = data_50["board"].astype('category')
data_50["school"] = data_50["school"].astype('category')
data_50["stream"] = data_50["stream"].astype('category')
data_50["co-curr"] = data_50["co-curr"].astype('category')
data_50["extra-curr"] = data_50["extra-curr"].astype('category')
data_50["interestedDomain"] = data_50["interestedDomain"].astype('category')
data_50["profCerti"] = data_50["profCerti"].astype('category')
data_50["personalDevCerti"] = data_50["personalDevCerti"].astype('category')
data_50["personality"] = data_50["personality"].astype('category')
data_50["job/study"] = data_50["job/study"].astype('category')
data_50["learningMode"] = data_50["learningMode"].astype('category')
data_50["SuggestedCarrer"] = data_50["SuggestedCarrer"].astype('category')

In [142]:
data_50["fin_back"] = data_50["fin_back"].cat.codes
data_50["medium"] = data_50["medium"].cat.codes
data_50["performace"] = data_50["performace"].cat.codes
data_50["board"] = data_50["board"].cat.codes
data_50["school"] = data_50["school"].cat.codes
data_50["stream"] = data_50["stream"].cat.codes
data_50["co-curr"] = data_50["co-curr"].cat.codes
data_50["extra-curr"] = data_50["extra-curr"].cat.codes
data_50["interestedDomain"] = data_50["interestedDomain"].cat.codes
data_50["profCerti"] = data_50["profCerti"].cat.codes
data_50["personalDevCerti"] = data_50["personalDevCerti"].cat.codes
data_50["personality"] = data_50["personality"].cat.codes
data_50["job/study"] = data_50["job/study"].cat.codes
data_50["learningMode"] = data_50["learningMode"].cat.codes
data_50["SuggestedCarrer"] = data_50["SuggestedCarrer"].cat.codes

Decision Tree

In [143]:
from sklearn import tree
from sklearn.model_selection import train_test_split
model_tree = tree.DecisionTreeClassifier()

In [144]:
output = data_50['SuggestedCarrer']
inputs = data_50.drop('SuggestedCarrer',axis=1)

In [145]:
X_train, X_test, y_train, y_test = train_test_split(inputs,output, test_size=0.33)

In [146]:
model_tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [147]:
pred_tree = model_tree.predict(X_test)
pred_tree

array([18,  2,  7, ...,  2,  8, 15], dtype=int8)

In [148]:
from sklearn.metrics import accuracy_score
accuracy_tree = accuracy_score(y_test,pred_tree)
accuracy_tree*100

5.03030303030303

SVM

In [149]:
from sklearn import svm
model_svm = svm.SVC()
model_svm.fit(X_train, y_train)   #------giving test data as input----#
pred_svm = model_svm.predict(X_test)
pred_svm

array([ 7, 13, 17, ..., 17,  2,  4], dtype=int8)

In [150]:
accuracy_svm = accuracy_score(y_test,pred_svm)
accuracy_svm*100

5.33939393939394

Naive Bayes

In [151]:
from sklearn.naive_bayes import GaussianNB 
model_NB = GaussianNB()
model_NB.fit(X_train,y_train)
pred_nb = model_NB.predict(X_test)
pred_nb

array([ 2, 13, 10, ..., 17, 16,  4], dtype=int8)

In [152]:
accuracy_nb = accuracy_score(y_test,pred_nb)
accuracy_nb*100

5.2

Smaller samples showed better results with DTs but larger samples showed better results with SVM