NUMPY TUTORIAL

NumPy is a general-purpose array processing package. It provides high performance multi dimensioanl array object, and toold for working with these arrays --- fundamental package for scientific computing with python

ARRAY  ::: a data structure thats stores homogeneous data -- the only difference betwen arrays and lists in Python  

In [1]:
import numpy as np

In [3]:
l = [1,2,3,4,5]
arr = np.array(l)
print(l,'list')
print(arr, 'array')

[1, 2, 3, 4, 5] list
[1 2 3 4 5] array


In [4]:
arr.shape

(5,)

In [10]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]
l3 = [12,34,56,78,90]

arr = np.array([l1,l2,l3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [12, 34, 56, 78, 90]])

In [6]:
arr.shape

(3, 5)

In [7]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 12, 34],
       [56, 78, 90]])

INDEXING

In [11]:
ar = np.array([1,2,3,4,5,6,7,8,9,0])
ar[3]

4

In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [12, 34, 56, 78, 90]])

In [13]:
arr[:,:] #all rows x column

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [12, 34, 56, 78, 90]])

In [14]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [15]:
arr[1:3,2:4]

array([[ 8,  9],
       [56, 78]])

In [16]:
arr2 = np.arange(0,10,step=2)
arr2

array([0, 2, 4, 6, 8])

In [17]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [19]:
ar1=ar
ar1[3] = 500
ar1 

array([  1,   2,   3, 500,   5,   6,   7,   8,   9,   0])

In [20]:
ar1=ar
ar1[3:] = 1500
ar1

array([   1,    2,    3, 1500, 1500, 1500, 1500, 1500, 1500, 1500])

In [21]:
ar2 = ar1.copy()

In [22]:
ar2

array([   1,    2,    3, 1500, 1500, 1500, 1500, 1500, 1500, 1500])

In [23]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])