In [1]:
import numpy as np

In [4]:
# Create 1D array
a = np.array([5,6,9])
a[1]

6

In [8]:
#creating 2-D array
a=np.array([[1,2],[3,4],[5,6]])
print(a)
a.ndim
            

[[1 2]
 [3 4]
 [5 6]]


2

In [9]:
#print bytesize of elements
a.itemsize #because integers hence prints 8bytes

8

In [10]:
a.dtype #says int64

dtype('int64')

In [13]:
a.size #no. of elements

6

In [14]:
a.shape #rows * columns

(3, 2)

In [16]:
#create array of all zeros
np.zeros((2,3))  #just mention the shape of array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#create array of all ones
np.ones((2,3))  #just mention the shape of array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#range() creates a list of numbers
l = range(5)
l[3]

3

In [20]:
l

range(0, 5)

In [22]:
##create an array
np.arange(1,5) #endlimit excluded

array([1, 2, 3, 4])

In [23]:
np.arange(1,5,2) #here 2 is step

array([1, 3])

In [25]:
#create an array of linearly spaced elements 
np.linspace(1,5,10)  #10 elemnets between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
#reshape
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [31]:
#flatten your array and make it 1D
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [32]:
a.min() #max(), sum() try

1

In [33]:
#sum of all elements in 1st row  
a.sum(axis=1)  #row = 1, column =0

array([ 3,  7, 11])

In [34]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [35]:
np.std(a) #standard deviation

1.707825127659933

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[5, 6],
       [7, 8]])

In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [41]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [43]:
a*b

array([[ 5, 12],
       [21, 32]])